apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnl-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fnl-api
  template:
    metadata:
      labels:
        app: fnl-api
    spec:
      containers:
        - name: fnl-api
          image: {{.Env.SERVICE_API_IMAGE_NAME}}
          ports:
            - containerPort: 3100
          env:
            - name: AZURE_CLIENT_ID
              value: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
            - name: AZURE_KEY_VAULT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: fnl-api-config
                  key: AZURE_KEY_VAULT_ENDPOINT
                  optional: false
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: fnl-api-config
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
                  optional: false
